### ISSUE TITLE
Question about access to router

### ISSUE THREAD

**Issue by ghost** [koutheir/speedport-w724v-external-ip-address#2]
Hey,
in your description it says i have to place the file in /etc/..., so it seems i have to get access to the routers internal filesystem. And so my quiestion is how you did this, because for now i have not found any possibility to get access to the router via ssh/telnet or ftp.

hope to hear from you an greetings from germany
github@msde

**Comment by koutheir** [comment]
Hi,
Thanks for the greetings `^_^`
I don't have access to the file system of the router (I hope I had that...). The directory `/etc/...` is on the file system of the computer that runs the script provided by this repository.
